enum WeChatError {
  // 查询ACCESS_TOKEN失败
  QUERY_ACCESS_TOKEN_ERROR = 'QUERY_ACCESS_TOKEN_ERROR',
  // 登录失败
  LOGIN_ERROR = 'LOGIN_ERROR',
  // 未找到openid
  NOT_FOUND_OPENID = 'NOT_FOUND_OPENID',
  // 关联失败
  ASSOCIATE_ERROR = 'ASSOCIATE_ERROR',
  // 身份验证失败
  AUTH_ERROR = 'AUTH_ERROR',
  // 未找到用户
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  // 已经关联过
  ALREADY_ASSOCIATED = 'ALREADY_ASSOCIATED',
}

export default WeChatError;